import {
  NButton,
  NCard,
  NCheckbox,
  NCollapse,
  NCollapseItem,
  NConfigProvider,
  NDatePicker,
  NFlex,
  NInput,
  NInputNumber,
  NLayout,
  NLayoutContent,
  NLayoutFooter,
  NLayoutHeader,
  NModal,
  NModalProvider,
  NScrollbar,
  NSelect,
  NSpace,
  NText,
  darkTheme,
  dateZhCN,
  zhCN,
  NAlert,
  NDescriptions,
  NDescriptionsItem,
  NTag,
  NDivider,
  NSpin,
  NTimePicker,
  NSwitch,
  NDialog,
  NIcon,
  NEmpty,
  NButtonGroup,
  NUpload,
  NTabPane,
  NTabs,
  NForm,
  NFormItem,
  NDataTable

} from "naive-ui";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const naiveUiComponents: Array<{ component: any; name: string }> = [
  { component: NButton, name: "n-button" },
  { component: NCard, name: "n-card" },
  { component: NCheckbox, name: "n-checkbox" },
  { component: NCollapse, name: "n-collapse" },
  { component: NCollapseItem, name: "n-collapse-item" },
  { component: NConfigProvider, name: "n-config-provider" },
  { component: NDatePicker, name: "n-date-picker" },
  { component: NFlex, name: "n-flex" },
  { component: NInput, name: "n-input" },
  { component: NInputNumber, name: "n-input-number" },
  { component: NLayout, name: "n-layout" },
  { component: NLayoutContent, name: "n-layout-content" },
  { component: NLayoutFooter, name: "n-layout-footer" },
  { component: NLayoutHeader, name: "n-layout-header" },
  { component: NModal, name: "n-modal" },
  { component: NModalProvider, name: "n-modal-provider" },
  { component: NScrollbar, name: "n-scrollbar" },
  { component: NSelect, name: "n-select" },
  { component: NSpace, name: "n-space" },
  { component: NText, name: "n-text" },
  { component: NAlert, name: "n-alert" },
  { component: NDescriptions, name: "n-descriptions" },
  { component: NDescriptionsItem, name: "n-descriptions-item" },
  { component: NTag, name: "n-tag" },
  { component: NDivider, name: "n-divider" },
  { component: NSpin, name: "n-spin" },
  { component: NTimePicker, name: "n-time-picker" },
  { component: NSwitch, name: "n-switch" },
  { component: NDialog, name: "n-dialog" },
  { component: NIcon, name: "n-icon" },
  { component: NEmpty, name: "n-empty" },
  { component: NButtonGroup, name: "n-button-group" },
  { component: NUpload, name: "n-upload" },
  { component: NTabPane, name: "n-tab-pane" },
  { component: NTabs, name: "n-tabs" },
  { component: NForm, name: "n-form" },
  { component: NFormItem, name: "n-form-item" },
  { component: NDataTable, name: "n-data-table" },
];

export const naiveConfig = {
  theme: darkTheme,
  locale: zhCN,
  dateLocale: dateZhCN,
};
